# Use the official Python base image
FROM python:3.11-slim

# Set working directory inside container
WORKDIR /app

# Copy your current folder into the container
COPY . .

# Install dependencies if you have a requirements.txt
# RUN pip install -r requirements.txt

# Run a command (optional)
CMD ["python3"]

